### ISSUE TITLE
Lifetime fix is missing from the changelog for 0.7.4

### ISSUE THREAD

**Issue by koute** [jeromefroe/lru-rs#132]
The recent safety fix https://github.com/jeromefroe/lru-rs/pull/128 is missing from the changelog.

Also, since it's a safety issue I'd argue the 0.7.3 should ideally be yanked and [reported to RustSec](https://github.com/RustSec/advisory-db/blob/master/CONTRIBUTING.md).

**Comment by jeromefroe** [comment]
Thank you for pointing this out! I just updated the changelog and yanked 0.7.3.

**Comment by jeromefroe** [comment]
And reported it to RustSec [here](https://github.com/rustsec/advisory-db/pull/1219).
