### ISSUE TITLE
Allow more liberal closure for `get_or_insert`

### ISSUE THREAD

**Issue by bluescreen303** [jeromefroe/lru-rs#142]
Currently, `get_or_insert` expects a `Fn`, but only calls it once (as expected). I have a case where if an item isn't found in the cache, it gets read from a file. Reading requires mutation (of the cursor), but **lru-rs** currently restricts closures to `Fn`, blocking functions that take a `&mut self`. Is there any reason for this? Can this be turned into `FnMut` or even `FnOnce`?

**Comment by jeromefroe** [comment]
@bluescreen303 good point, `FnOnce` should be sufficient and would be the most flexible. I just opened #143 to address. If that change looks good to you, I'll land it and cut a new release.

**Comment by bluescreen303** [comment]
looks good to me. thanks!
