### ISSUE TITLE
Could we have a new version with the updated `hashbrown` (and maybe others) dependency ?

### ISSUE THREAD

**Issue by poliorcetics** [jeromefroe/lru-rs#147]

**Comment by jeromefroe** [comment]
Hey @poliorcetics!  Sorry for the delay here, I just published a new version, [`v0.7.8`](https://crates.io/crates/lru), with the updated version of `hashbrown`.

**Comment by poliorcetics** [comment]
No problem, thanks a lot for the (very) quick response and the crate itself :) !
