### ISSUE TITLE
Missing lifetime specifier in try_get_or_insert_mut?

### ISSUE THREAD

**Issue by felipou** [jeromefroe/lru-rs#182]
https://github.com/jeromefroe/lru-rs/blob/df4d7829fb555e70463a00e17871a4ac0f1ca5b4/src/lib.rs#L636

Shouldn't the lifetime of the self reference also be `'a`? Like `get_or_insert_mut` and `get_mut`, for example. This is what would link the lifetime to the cache, and prevent us from getting two mut references to the same value, right? As it is I guess we could get two mutable references to the same value (haven't really tried that though).

**Comment by jeromefroe** [comment]
Oh, good catch, I believe it should be!
