### ISSUE TITLE
Support for getting all the keys

### ISSUE THREAD

**Issue by rohitjoshi** [jeromefroe/lru-rs#19]
It would be good to have support to retrieve all the keys. My use-case is to persist all the keys so at startup, read the keys from DB and warm up the cache.

**Comment by jeromefroe** [comment]
That sounds like a great idea! Would implementing the [`IntoIterator`](https://doc.rust-lang.org/std/iter/trait.IntoIterator.html) suffice for your use case?

**Comment by jeromefroe** [comment]
Hey, I just landed #20 which adds support for an iterator over the entries in a cache. Let me know if that works for you when you get a chance and if so I'll cut a new release.

**Comment by rohitjoshi** [comment]
👍 works great. Thank you.

**Comment by jeromefroe** [comment]
Great, glad to hear it! I also just released a new version ([0.1.11](https://crates.io/crates/lru/0.1.11)) to cargo with the changes.
