### ISSUE TITLE
Minor optimization: Passing Key as a reference for put

### ISSUE THREAD

**Issue by rohitjoshi** [jeromefroe/lru-rs#25]
Can we pass the key as a reference and copy/clone if needed?

Looking at the below code, if a key already exists, we override the value. We don't have to clone the key which will save copying of the key data. 

https://github.com/jeromefroe/lru-rs/blob/master/src/lib.rs#L195

**Comment by rohitjoshi** [comment]
editing issue title

**Comment by jeromefroe** [comment]
That's an interesting idea! Instead of changing the current implementation of `put` though, what do you think about adding a new method, `put_ref` perhaps, that takes a clonable reference? For example:

```
impl<K: Hash + Eq + Clone, V> LruCache<K, V> {
    pub fn put_ref(&mut self, k: K, v: V) {
        // ...
    }
}
```

**Comment by rohitjoshi** [comment]
I think this is a minor improvement which only helps if key already exist but makes interface complex. So may not required. So closing this.
