### ISSUE TITLE
get_mut support

### ISSUE THREAD

**Issue by g2p** [jeromefroe/lru-rs#3]
Please add a `get_mut` method, for getting mutable values out of the cache.

**Comment by jeromefroe** [comment]
Hey! Thanks for the interest, I'm a little tied up this week, but I'll look into adding `get_mut` method this weekend.

**Comment by jeromefroe** [comment]
Hey, this is long overdue, but I found had a chance to get back to this crate (and Rust in general) this weekend. I just added a `get_mut` method and released `0.1.5` which contains it. Sorry for the delay and thanks again for the interest!

**Comment by niklasf** [comment]
Thank you @jeromefroe, much appreciated!
