### ISSUE TITLE
Feature request: Change capacity at runtime

### ISSUE THREAD

**Issue by niklasf** [jeromefroe/lru-rs#4]
Hi, do you think it would be possible to change the capacity of the cache at runtime?

**Comment by jeromefroe** [comment]
Hey, thanks for the interest! I'd love to get back to this, but I just haven't had the time. With that being said I'll try to take a look in the coming weeks. Thanks again!

**Comment by jeromefroe** [comment]
Hey! Sorry for the delay, I just added a `resize` method to the cache and released version `0.1.6`. Thanks again for the interest!
