### ISSUE TITLE
Add peek_mut method

### ISSUE THREAD

**Issue by gliderkite** [jeromefroe/lru-rs#53]
Is there any specific reason why `LrUCache` does not provide a `peek_mut` method?

We already have `get`, `get_mut` and `peek`, it would be nice to add the equivalent `peek_mut` method to return the mutable reference corresponding to the key in the cache or `None` if it is not present in the cache, without having to update the LRU list.

**Comment by jeromefroe** [comment]
Hey! Thanks for pointing this out, there's no specific reason, it's just that's no has requested it yet :) I think it should be fairly straightforward to implement though, so I'll aim to take a look over the weekend.

**Comment by gliderkite** [comment]
Thanks! Let me know in case support is needed for this :)

**Comment by jeromefroe** [comment]
@gliderkite I just released [version 0.3.0](https://crates.io/crates/lru) which adds a `peek_mut` method. Let me know if that work.
