### ISSUE TITLE
Possible issue found with Miri

### ISSUE THREAD

**Issue by Firstyear** [jeromefroe/lru-rs#73]
Hi there,

I was using LruCache in a project that I regularly scan with Miri and I recieved the following report:

```
error: Undefined Behavior: type validation failed: encountered undefined pointer at .value.prev
    --> /home/william/.rustup/toolchains/nightly-2020-03-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/mem/maybe_uninit.rs:502:34
     |
502  |         ManuallyDrop::into_inner(self.value)
     |                                  ^^^^^^^^^^ type validation failed: encountered undefined pointer at .value.prev
     |
     = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
     = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
     = note: inside call to `std::mem::MaybeUninit::<lru::LruEntry<usize, usize>>::assume_init` at /home/william/.cargo/registry/src/github.com-1ecc6299db9ec823/lru-0.4.3/src/lib.rs:222:51
     = note: inside call to `lru::LruCache::<usize, usize>::construct` at /home/william/.cargo/registry/src/github.com-1ecc6299db9ec823/lru-0.4.3/src/lib.rs:183:9
note: inside call to `lru::LruCache::<usize, usize>::new` at src/cache/arc/mod.rs:391:21
    --> src/cache/arc/mod.rs:391:21
     |
391  |             tlocal: LruCache::new(self.read_max),
     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I'm wondering if this is an issue that you are aware of? 

Thanks!

**Comment by jeromefroe** [comment]
Hey! Thanks for reporting this. Can you also provide the command that you're using to run `miri`? When I run it locally myself I don't get any errors:

```bash
$ cargo miri run --target x86_64-unknown-linux-gnu
   Compiling compiler_builtins v0.1.27
    Checking core v0.0.0 (/Users/jeromefroelich/.rustup/toolchains/nightly-2020-05-09-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore)
   Compiling cc v1.0.50
   Compiling libc v0.2.69
   Compiling autocfg v0.1.7
   Compiling std v0.0.0 (/Users/jeromefroelich/.rustup/toolchains/nightly-2020-05-09-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd)
   Compiling hashbrown v0.6.2
   Compiling backtrace-sys v0.1.37
   Compiling unwind v0.0.0 (/Users/jeromefroelich/.rustup/toolchains/nightly-2020-05-09-x86_64-apple-darwin/lib/rustlib/src/rust/src/libunwind)
    Checking rustc-std-workspace-core v1.99.0 (/Users/jeromefroelich/.rustup/toolchains/nightly-2020-05-09-x86_64-apple-darwin/lib/rustlib/src/rust/src/tools/rustc-std-workspace-core)
    Checking cfg-if v0.1.10
    Checking alloc v0.0.0 (/Users/jeromefroelich/.rustup/toolchains/nightly-2020-05-09-x86_64-apple-darwin/lib/rustlib/src/rust/src/liballoc)
    Checking rustc-demangle v0.1.16
    Checking panic_abort v0.0.0 (/Users/jeromefroelich/.rustup/toolchains/nightly-2020-05-09-x86_64-apple-darwin/lib/rustlib/src/rust/src/libpanic_abort)
    Checking backtrace v0.3.46
    Checking rustc-std-workspace-alloc v1.99.0 (/Users/jeromefroelich/.rustup/toolchains/nightly-2020-05-09-x86_64-apple-darwin/lib/rustlib/src/rust/src/tools/rustc-std-workspace-alloc)
    Checking panic_unwind v0.0.0 (/Users/jeromefroelich/.rustup/toolchains/nightly-2020-05-09-x86_64-apple-darwin/lib/rustlib/src/rust/src/libpanic_unwind)
    Finished release [optimized] target(s) in 19.89s
    Checking rustc-std-workspace-std v1.99.0 (/Users/jeromefroelich/.rustup/toolchains/nightly-2020-05-09-x86_64-apple-darwin/lib/rustlib/src/rust/src/tools/rustc-std-workspace-std)
    Checking proc_macro v0.0.0 (/Users/jeromefroelich/.rustup/toolchains/nightly-2020-05-09-x86_64-apple-darwin/lib/rustlib/src/rust/src/libproc_macro)
    Checking term v0.0.0 (/Users/jeromefroelich/.rustup/toolchains/nightly-2020-05-09-x86_64-apple-darwin/lib/rustlib/src/rust/src/libterm)
    Checking unicode-width v0.1.6
    Checking getopts v0.2.21
    Checking test v0.0.0 (/Users/jeromefroelich/.rustup/toolchains/nightly-2020-05-09-x86_64-apple-darwin/lib/rustlib/src/rust/src/libtest)
    Finished release [optimized] target(s) in 2.58s
```

**Comment by Firstyear** [comment]
Hey there,

I think the issue is here https://github.com/jeromefroe/lru-rs/blob/master/src/lib.rs#L222

It looks like you are making a new MaybeUninit, and then immediately calling https://doc.rust-lang.org/std/mem/union.MaybeUninit.html#method.assume_init on it, which can't be valid because you don't have an LruEntry inside the MaybeUninit at that point I think. This is what appears to confuse the ManualDrop::into_inner because there is no pointer inside of the MaybeUninit at that point. 

Anyway, I'm running this from my `concread` library, and the commands would be:

```
git clone https://github.com/Firstyear/concread.git
cargo clean && cargo miri setup && cargo miri test -- -Zmiri-disable-isolation -- test_cache_concurrent_cursed_1
```

Which should give you the error.

Hope that helps, and thanks for your time :)

**Comment by jeromefroe** [comment]
Ahh, so I believe that should be okay because we [implement `Drop` for the `LruCache`](https://github.com/jeromefroe/lru-rs/blob/master/src/lib.rs#L738) where we handle the `head` and `tail` entries specially. We never initialize `head` and `tail` normally, but that's okay because we only ever use the `next` and `prev` fields of them.

**Comment by Firstyear** [comment]
I guess the challenge is while it's okay and we know it's okay, convincing miri to agree with that situation :) 

Maybe it's not my place to say, but perhaps the way to resolve this is have MaybeUninit K, V in the LruEntry itself rather than in the Box so you can initialise the sigil nodes, or to remove the sigil nodes and set head/tail to ptr::null_mut() and change the double linked list algorithm to suit.

**Comment by jeromefroe** [comment]
Yea, is there a way to exclude lines from Miri? That might be the simplest solution. PR's are also more than welcome if you have any other implementation ideas :)

**Comment by Firstyear** [comment]
I think there are some ways to do that ... let me look into the miri exclusion. But I'm also happy to put in a PR to improve this, so hopefully I have some time this week :)

Thanks for your patience with me on this!

**Comment by Firstyear** [comment]
This PR relates to this issue https://github.com/jeromefroe/lru-rs/pull/74 

Thanks!

**Comment by Firstyear** [comment]
Also as a note, it's not possible to provide a miri exclusion beyond the granularity of excluding a whole test, so we can't just mask this one area from examination.

**Comment by jeromefroe** [comment]
Closing this now that #74 has landed.
